// Objective-C API for talking to github.com/EbrahimTahernejad/xray-mobile Go package.
//   gobind -lang=objc github.com/EbrahimTahernejad/xray-mobile
//
// File is generated by gobind. Do not edit.

#ifndef __XRay_H__
#define __XRay_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol XRayLogger;
@class XRayLogger;

@protocol XRayLogger <NSObject>
- (void)logInput:(NSString* _Nullable)s;
@end

FOUNDATION_EXPORT NSString* _Nonnull XRayGetVersion(void);

FOUNDATION_EXPORT BOOL XRayMeasureDelay(NSString* _Nullable url, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL XRayMeasureOutboundDelay(NSString* _Nullable ConfigureFileContent, NSString* _Nullable url, int64_t* _Nullable ret0_, NSError* _Nullable* _Nullable error);

/**
 * QueryStats returns all traffic counters as "name>>>value\n" lines.
Uses VisitCounters which is available in xray-core features/stats.Manager.
Caller parses "uplink" and "downlink" from counter names.
 */
FOUNDATION_EXPORT NSString* _Nonnull XRayQueryStats(NSString* _Nullable tag);

/**
 * SetAssetLocation configures the directory used by Xray-core to load runtime
assets such as geoip.dat and geosite.dat.

This function deliberately updates the environment from Go. On iOS, calling
setenv from Swift after the Go runtime has initialized does not update the
environment observed by Go's os.LookupEnv. Passing an empty path restores
Xray's default executable-directory lookup.
 */
FOUNDATION_EXPORT BOOL XRaySetAssetLocation(NSString* _Nullable directory, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void XRaySetMemoryLimit(void);

FOUNDATION_EXPORT BOOL XRayStart(NSData* _Nullable config, id<XRayLogger> _Nullable logger, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void XRayStop(void);

@class XRayLogger;

@interface XRayLogger : NSObject <goSeqRefInterface, XRayLogger> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)logInput:(NSString* _Nullable)s;
@end

#endif
