name: flutter_vless_platform_interface
description: A common platform interface for the flutter_vless plugin.
version: 1.1.1
homepage: https://tfox.dev
repository: https://github.com/XIIIFOX/flutter_vless
issue_tracker: https://github.com/XIIIFOX/flutter_vless/issues
documentation: https://github.com/XIIIFOX/flutter_vless/blob/main/doc/api.md
funding:
  - https://tfox.dev

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
